apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo2cd
  namespace: argo2cd
spec:
  project: default

  source:
    repoURL: https://github.com/siirresh/argocd.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true 

    automated: 
      selfHeal: true
      prune: true 
